###
POST http://localhost:8000/book
Content-Type: application/json

{
  "name":"Steve Jeong",
  "email":"jst0930@gmail.com"
}

###
GET http://localhost:8000

###
GET http://localhost:8000/book

###
GET http://localhost:8000/book/1